const cards: Card[] = [
  {
    cardId: 'card1',
    cheatsheetId: 'cs1',
    title: 'Using Placeholders',
    summary: 'Understanding and effectively using placeholders in prompt engineering.',
    order: 0,
    size: 'large',
  },
  {
    cardId: 'card2',
    cheatsheetId: 'cs2',
    title: 'Crafting Engaging Prompts',
    summary: 'Strategies for creating engaging and effective prompts for marketing.',
    order: 1,
    size: 'medium',
  },
  {
    cardId: 'card3',
    cheatsheetId: 'cs1',
    title: 'Prompt Efficiency',
    summary: 'Maximizing the effectiveness of prompts with minimal complexity.',
    order: 2,
    size: 'medium',
  },
  {
    cardId: 'card4',
    cheatsheetId: 'cs1',
    title: 'User Intent Recognition',
    summary: 'Strategies for understanding and addressing user intent in prompts.',
    order: 3,
    size: 'medium',
  },
  {
    cardId: 'card5',
    cheatsheetId: 'cs1',
    title: 'Contextual Prompts',
    summary: 'Leveraging context to create more relevant and impactful prompts.',
    order: 4,
    size: 'large',
  },
  {
    cardId: 'card6',
    cheatsheetId: 'cs2',
    title: 'Brand Voice Integration',
    summary:
      "Incorporating your brand's voice into prompt design for a consistent user experience.",
    order: 2,
    size: 'medium',
  },
  {
    cardId: 'card7',
    cheatsheetId: 'cs2',
    title: 'Data-Driven Prompts',
    summary: 'Utilizing data to craft more effective and targeted prompts.',
    order: 3,
    size: 'small',
  },
  {
    cardId: 'card8',
    cheatsheetId: 'cs2',
    title: 'Multilingual Prompts',
    summary: 'Creating and optimizing prompts for a multilingual audience.',
    order: 4,
    size: 'small',
  },
  {
    cardId: 'card9',
    cheatsheetId: 'cs2',
    title: 'Prompt Personalization',
    summary: 'Techniques for personalizing prompts to increase user engagement and satisfaction.',
    order: 5,
    size: 'large',
  },
];

export default cards;
