import categories from '@/mockup-data/categories';

const items: Item[] = [
  {
    itemId: 'item1',
    cardId: 'card1',
    title: 'Placeholder Syntax',
    description:
      'Learn the syntax for placeholders and how they can be used to generate dynamic responses.',
    example: 'Hello, {{name}}! How can I assist you today?',
    syntax: 'Placeholder syntax: {{variable}}',
    created_At: new Date('2024-04-02'),
    updated_At: new Date('2024-04-02'),
    tags: [categories[0], categories[2]],
  },
  {
    itemId: 'item2',
    cardId: 'card2',
    title: 'Engagement Tricks',
    description: "Techniques to ensure your prompts grab and hold the reader's attention.",
    example:
      "Imagine you're speaking directly to the customer. How would you phrase your question?",
    syntax: 'Use direct and engaging language.',
    created_At: new Date('2024-04-06'),
    updated_At: new Date('2024-04-06'),
    tags: [categories[1]],
  },
  {
    itemId: 'item3',
    cardId: 'card4',
    title: 'Conditional Logic in Prompts',
    description: 'Incorporate conditional logic to create more dynamic and responsive prompts.',
    example: "If the user mentions 'weather', provide the current weather forecast.",
    syntax: 'Conditional syntax: if(condition) { action }',
    created_At: new Date('2024-04-07'),
    updated_At: new Date('2024-04-07'),
    tags: [categories[0], categories[2]],
  },
  {
    itemId: 'item4',
    cardId: 'card4',
    title: 'Looping Structures',
    description: 'Utilize loops to generate repetitive or iterative content within your prompts.',
    example: 'For each item in the list, generate a sentence describing it.',
    syntax: 'Loop syntax: for(item in list) { action }',
    created_At: new Date('2024-04-08'),
    updated_At: new Date('2024-04-08'),
    tags: [categories[0]],
  },
  {
    itemId: 'item5',
    cardId: 'card4',
    title: 'Prompt Tone and Style',
    description: 'Adjust the tone and style of your prompts to match your audience and objectives.',
    example:
      'For a professional audience, use a formal tone. For a younger audience, a casual tone might be more effective.',
    syntax: 'Tone and style adjustments in prompts.',
    created_At: new Date('2024-04-09'),
    updated_At: new Date('2024-04-09'),
    tags: [categories[1], categories[2]],
  },
  {
    itemId: 'item6',
    cardId: 'card5',
    title: 'Variable Interpolation',
    description: 'Dynamically insert variables into your prompts for personalized responses.',
    example: "Hello, ${userName}! Here's your personalized news update.",
    syntax: 'Variable interpolation syntax: ${variable}',
    created_At: new Date('2024-04-10'),
    updated_At: new Date('2024-04-10'),
    tags: [categories[0]],
  },
  {
    itemId: 'item7',
    cardId: 'card6',
    title: 'Question Phrasing',
    description: 'Craft questions in your prompts that are clear, concise, and easy to respond to.',
    example: "Instead of 'Tell me about your day,' ask 'How was your day?'",
    syntax: 'Question phrasing techniques.',
    created_At: new Date('2024-04-11'),
    updated_At: new Date('2024-04-11'),
    tags: [categories[1], categories[2]],
  },
  {
    itemId: 'item8',
    cardId: 'card6',
    title: 'Integrating APIs',
    description:
      'Enhance your prompts by integrating external APIs for dynamic content generation.',
    example:
      "Use a weather API to include the current weather in your greeting: 'Good morning! It's sunny in San Francisco today.'",
    syntax: 'API integration in prompts.',
    created_At: new Date('2024-04-12'),
    updated_At: new Date('2024-04-12'),
    tags: [categories[0]],
  },
  {
    itemId: 'item9',
    cardId: 'card6',
    title: 'User Feedback Incorporation',
    description:
      'Learn how to adapt your prompts based on user feedback for continuous improvement.',
    example: 'If a user frequently asks for clarifications, consider simplifying your prompts.',
    syntax: 'Adapting prompts based on feedback.',
    created_At: new Date('2024-04-13'),
    updated_At: new Date('2024-04-13'),
    tags: [categories[1], categories[2]],
  },
  {
    itemId: 'item10',
    cardId: 'card8',
    title: 'Debugging Prompts',
    description:
      'Identify and fix common issues in prompt engineering to improve response quality.',
    example: 'If a prompt is too vague, add specific examples or clarify the intended action.',
    syntax: 'Debugging techniques for prompts.',
    created_At: new Date('2024-04-14'),
    updated_At: new Date('2024-04-14'),
    tags: [categories[0]],
  },
  {
    itemId: 'item11',
    cardId: 'card8',
    title: 'Narrative Structure',
    description: 'Build a compelling narrative within your prompts to engage users effectively.',
    example:
      'Start with a brief introduction, present a problem, and then guide the user to the solution.',
    syntax: 'Structuring prompts with a narrative arc.',
    created_At: new Date('2024-04-15'),
    updated_At: new Date('2024-04-15'),
    tags: [categories[1], categories[2]],
  },
  {
    itemId: 'item12',
    cardId: 'card7',
    title: 'Prompt Optimization',
    description: 'Techniques for optimizing your prompts for better clarity and response accuracy.',
    example: 'Use specific, targeted questions rather than broad, general inquiries.',
    syntax: 'Best practices for optimizing prompts.',
    created_At: new Date('2024-04-16'),
    updated_At: new Date('2024-04-16'),
    tags: [categories[0], categories[2]],
  },
  {
    itemId: 'item13',
    cardId: 'card3',
    title: 'Minimizing Prompt Length',
    description: 'Strategies to reduce prompt length while maintaining effectiveness.',
    example: 'Instead of a lengthy description, use concise phrases that convey the same message.',
    syntax: 'Techniques for reducing prompt length.',
    created_At: new Date('2024-04-17'),
    updated_At: new Date('2024-04-17'),
    tags: [categories[0], categories[2]],
  },
  {
    itemId: 'item14',
    cardId: 'card3',
    title: 'Prompt Precision',
    description: 'Ensuring your prompts are precise and lead to expected outcomes.',
    example: 'Specify the exact information needed in your prompt to avoid ambiguous responses.',
    syntax: 'Best practices for crafting precise prompts.',
    created_At: new Date('2024-04-18'),
    updated_At: new Date('2024-04-18'),
    tags: [categories[0]],
  },
  {
    itemId: 'item15',
    cardId: 'card4',
    title: 'Identifying User Intent',
    description: 'Techniques to discern and align your prompts with user intent.',
    example:
      "Use targeted questions to clarify user intent when it's not clear from the initial input.",
    syntax: 'Strategies for identifying user intent.',
    created_At: new Date('2024-04-19'),
    updated_At: new Date('2024-04-19'),
    tags: [categories[0], categories[2]],
  },
  {
    itemId: 'item16',
    cardId: 'card4',
    title: 'Responding to Ambiguous Queries',
    description: 'How to design prompts that handle and clarify ambiguous user queries.',
    example: 'When faced with ambiguity, prompt the user for more specific information.',
    syntax: 'Handling ambiguity in user queries.',
    created_At: new Date('2024-04-20'),
    updated_At: new Date('2024-04-20'),
    tags: [categories[0]],
  },
  {
    itemId: 'item17',
    cardId: 'card5',
    title: 'Leveraging User Context',
    description: 'Incorporating user context into prompts for more personalized responses.',
    example:
      'If the user is browsing a product, tailor prompts to offer more information on similar items.',
    syntax: 'Utilizing user context in prompts.',
    created_At: new Date('2024-04-21'),
    updated_At: new Date('2024-04-21'),
    tags: [categories[0], categories[2]],
  },
  {
    itemId: 'item18',
    cardId: 'card6',
    title: 'Consistent Brand Voice',
    description: "Ensuring your prompts reflect your brand's voice and values consistently.",
    example: 'If your brand is playful, use light-hearted language and jokes in your prompts.',
    syntax: 'Maintaining brand voice in prompts.',
    created_At: new Date('2024-04-22'),
    updated_At: new Date('2024-04-22'),
    tags: [categories[1]],
  },
  {
    itemId: 'item19',
    cardId: 'card7',
    title: 'Analyzing Response Data',
    description: 'Utilize response data to refine and enhance your prompt strategies.',
    example:
      "Review how users respond to different prompts and adjust based on what's most effective.",
    syntax: 'Data analysis techniques for prompt optimization.',
    created_At: new Date('2024-04-23'),
    updated_At: new Date('2024-04-23'),
    tags: [categories[1], categories[2]],
  },
  {
    itemId: 'item20',
    cardId: 'card8',
    title: 'Handling Multiple Languages',
    description:
      'Best practices for creating prompts that are effective across different languages.',
    example: 'Consider cultural nuances when crafting prompts to ensure they translate well.',
    syntax: 'Multilingual prompt creation guidelines.',
    created_At: new Date('2024-04-24'),
    updated_At: new Date('2024-04-24'),
    tags: [categories[2]],
  },
  {
    itemId: 'item21',
    cardId: 'card9',
    title: 'User-specific Customization',
    description: 'Techniques for customizing prompts based on individual user data.',
    example: "Use the user's browsing history to make prompts more relevant and engaging.",
    syntax: 'Customizing prompts for individual users.',
    created_At: new Date('2024-04-25'),
    updated_At: new Date('2024-04-25'),
    tags: [categories[1], categories[2]],
  },
  {
    itemId: 'item22',
    cardId: 'card9',
    title: 'Evolving with User Interactions',
    description: 'Adapting your prompts over time based on continuous user interaction.',
    example:
      'If a user consistently interacts with a specific type of prompt, increase the frequency of similar prompts.',
    syntax: 'Dynamic adaptation of prompts to user behavior.',
    created_At: new Date('2024-04-26'),
    updated_At: new Date('2024-04-26'),
    tags: [categories[1]],
  },
];

export default items;
