const items: Item[] = [
  {
    itemId: 'item1',
    cardId: 'card1',
    title: 'Analyst',
    value: 'Analyst',
    order: 1,
  },
  {
    itemId: 'item2',
    cardId: 'card1',
    title: 'Teacher',
    value: 'Teacher',
    order: 2,
  },
  {
    itemId: 'item3',
    cardId: 'card1',
    title: 'Marketer',
    value: 'Marketer',
    order: 3,
  },
  {
    itemId: 'item4',
    cardId: 'card1',
    title: 'Advertiser',
    value: 'Advertiser',
    order: 4,
  },
  {
    itemId: 'item5',
    cardId: 'card1',
    title: 'Mindset Coach',
    value: 'Mindset Coach',
    order: 5,
  },
  {
    itemId: 'item6',
    cardId: 'card1',
    title: 'Therapist',
    value: 'Therapist',
    order: 6,
  },
  {
    itemId: 'item7',
    cardId: 'card1',
    title: 'Journalist',
    value: 'Journalist',
    order: 7,
  },
  {
    itemId: 'item8',
    cardId: 'card1',
    title: 'Inventor',
    value: 'Inventor',
    order: 8,
  },
  {
    itemId: 'item9',
    cardId: 'card1',
    title: 'Lawyer',
    value: 'Lawyer',
    order: 9,
  },
  {
    itemId: 'item10',
    cardId: 'card1',
    title: 'Ghostwriter',
    value: 'Ghostwriter',
    order: 10,
  },
  {
    itemId: 'item11',
    cardId: 'card1',
    title: 'Website Designer',
    value: 'Website Designer',
    order: 11,
  },
  {
    itemId: 'item12',
    cardId: 'card1',
    title: 'Best Selling Author',
    value: 'Best Selling Author',
    order: 12,
  },
  {
    itemId: 'item13',
    cardId: 'card1',
    title: 'Chief Financial Officer',
    value: 'Chief Financial Officer',
    order: 13,
  },
  {
    itemId: 'item14',
    cardId: 'card1',
    title: 'Expert Copywriter',
    value: 'Expert Copywriter',
    order: 14,
  },
  {
    itemId: 'item15',
    cardId: 'card1',
    title: 'Prompt Engineer',
    value: 'Prompt Engineer',
    order: 15,
  },
  {
    itemId: 'item16',
    cardId: 'card1',
    title: 'Accountant',
    value: 'Accountant',
    order: 16,
  },
  {
    itemId: 'item17',
    cardId: 'card1',
    title: 'Project Manager',
    value: 'Project Manager',
    order: 17,
  },
  {
    itemId: 'item18',
    cardId: 'card1',
    title: 'Sports Coach',
    value: 'Sports Coach',
    order: 18,
  },
  {
    itemId: 'item19',
    cardId: 'card1',
    title: 'Financial Analyst',
    value: 'Financial Analyst',
    order: 19,
  },
  {
    itemId: 'item20',
    cardId: 'card1',
    title: 'Full Stack Developer',
    value: 'Full Stack Developer',
    order: 20,
  },
  {
    itemId: 'item21',
    cardId: 'card1',
    title: 'Linux Terminal',
    value: 'Linux Terminal',
    order: 21,
  },
  {
    itemId: 'item22',
    cardId: 'card1',
    title: '"Position" Interviewer',
    value: '"Position" Interviewer',
    order: 22,
  },
  {
    itemId: 'item23',
    cardId: 'card1',
    title: 'Excel Sheet',
    value: 'Excel Sheet',
    order: 23,
  },
  {
    itemId: 'item24',
    cardId: 'card1',
    title: 'Plagiarism Checker',
    value: 'Plagiarism Checker',
    order: 24,
  },
  {
    itemId: 'item25',
    cardId: 'card1',
    title: 'Relationship Coach',
    value: 'Relationship Coach',
    order: 25,
  },
  {
    itemId: 'item26',
    cardId: 'card1',
    title: 'Recruiter',
    value: 'Recruiter',
    order: 26,
  },
  {
    itemId: 'item27',
    cardId: 'card1',
    title: 'JavaScript Console',
    value: 'JavaScript Console',
    order: 27,
  },
  {
    itemId: 'item1',
    cardId: 'card2',
    title: 'Headline',
    value: 'Headline',
    order: 1,
  },
  {
    itemId: 'item2',
    cardId: 'card2',
    title: 'Article',
    value: 'Article',
    order: 2,
  },
  {
    itemId: 'item3',
    cardId: 'card2',
    title: 'Essay',
    value: 'Essay',
    order: 3,
  },
  {
    itemId: 'item4',
    cardId: 'card2',
    title: 'Book Outline',
    value: 'Book Outline',
    order: 4,
  },
  {
    itemId: 'item5',
    cardId: 'card2',
    title: 'Email Sequence',
    value: 'Email Sequence',
    order: 5,
  },
  {
    itemId: 'item6',
    cardId: 'card2',
    title: 'Social Media Post',
    value: 'Social Media Post',
    order: 6,
  },
  {
    itemId: 'item7',
    cardId: 'card2',
    title: 'Product Description',
    value: 'Product Description',
    order: 7,
  },
  {
    itemId: 'item8',
    cardId: 'card2',
    title: 'Cover Letter',
    value: 'Cover Letter',
    order: 8,
  },
  {
    itemId: 'item9',
    cardId: 'card2',
    title: 'Blog Post',
    value: 'Blog Post',
    order: 9,
  },
  {
    itemId: 'item10',
    cardId: 'card2',
    title: 'SEO Keywords',
    value: 'SEO Keywords',
    order: 10,
  },
  {
    itemId: 'item11',
    cardId: 'card2',
    title: 'Summary',
    value: 'Summary',
    order: 11,
  },
  {
    itemId: 'item12',
    cardId: 'card2',
    title: 'Video Script',
    value: 'Video Script',
    order: 12,
  },
  {
    itemId: 'item13',
    cardId: 'card2',
    title: 'Recipe',
    value: 'Recipe',
    order: 13,
  },
  {
    itemId: 'item14',
    cardId: 'card2',
    title: 'Sales Copy',
    value: 'Sales Copy',
    order: 14,
  },
  {
    itemId: 'item15',
    cardId: 'card2',
    title: 'Analysis',
    value: 'Analysis',
    order: 15,
  },
  {
    itemId: 'item16',
    cardId: 'card2',
    title: 'Ad Copy',
    value: 'Ad Copy',
    order: 16,
  },
  {
    itemId: 'item17',
    cardId: 'card2',
    title: 'Web Page',
    value: 'Web Page',
    order: 17,
  },
  {
    itemId: 'item1',
    cardId: 'card3',
    title: 'A Table',
    value: 'A Table',
    order: 1,
  },
  {
    itemId: 'item2',
    cardId: 'card3',
    title: 'A List',
    value: 'A List',
    order: 2,
  },
  {
    itemId: 'item4',
    cardId: 'card3',
    title: 'MaY',
    value: 'MaY',
    order: 4,
  },
  {
    itemId: 'item5',
    cardId: 'card3',
    title: 'Code',
    value: 'Code',
    order: 5,
  },
  {
    itemId: 'item6',
    cardId: 'card3',
    title: 'Spreadsheet',
    value: 'Spreadsheet',
    order: 6,
  },
  {
    itemId: 'item7',
    cardId: 'card3',
    title: 'Graphs',
    value: 'Graphs',
    order: 7,
  },
  {
    itemId: 'item8',
    cardId: 'card3',
    title: 'CSV file',
    value: 'CSV file',
    order: 8,
  },
  {
    itemId: 'item9',
    cardId: 'card3',
    title: 'Plain Text file',
    value: 'Plain Text file',
    order: 9,
  },
  {
    itemId: 'item10',
    cardId: 'card3',
    title: 'JSON',
    value: 'JSON',
    order: 10,
  },
  {
    itemId: 'item11',
    cardId: 'card3',
    title: 'Rich Text',
    value: 'Rich Text',
    order: 11,
  },
  {
    itemId: 'item12',
    cardId: 'card3',
    title: 'PDF',
    value: 'PDF',
    order: 12,
  },
  {
    itemId: 'item13',
    cardId: 'card3',
    title: 'XML',
    value: 'XML',
    order: 13,
  },
  {
    itemId: 'item14',
    cardId: 'card3',
    title: 'Markdown',
    value: 'Markdown',
    order: 14,
  },
  {
    itemId: 'item15',
    cardId: 'card3',
    title: 'Gantt Chart',
    value: 'Gantt Chart',
    order: 15,
  },
  {
    itemId: 'item16',
    cardId: 'card3',
    title: 'Word Cloud',
    value: 'Word Cloud',
    order: 16,
  },
  {
    itemId: 'item17',
    cardId: 'card3',
    title: 'Emojis',
    value: 'Emojis',
    order: 17,
  },
  {
    itemId: 'item18',
    cardId: 'card3',
    title: 'An Analogy',
    value: 'An Analogy',
    order: 18,
  },
  {
    itemId: 'item19',
    cardId: 'card3',
    title: 'Bullet Points',
    value: 'Bullet Points',
    order: 19,
  },
  {
    itemId: 'item1',
    cardId: 'card4',
    title: 'Use poetic language',
    value: 'Use poetic language',
    order: 1,
  },
  {
    itemId: 'item2',
    cardId: 'card4',
    title: 'Adopt a formal tone',
    value: 'Adopt a formal tone',
    order: 2,
  },
  {
    itemId: 'item3',
    cardId: 'card4',
    title: 'Write short sentences',
    value: 'Write short sentences',
    order: 3,
  },
  {
    itemId: 'item4',
    cardId: 'card4',
    title: 'Code only in HTML/CSS',
    value: 'Code only in HTML/CSS',
    order: 4,
  },
  {
    itemId: 'item5',
    cardId: 'card4',
    title: 'Use Shakespearian style',
    value: 'Use Shakespearian style',
    order: 5,
  },
  {
    itemId: 'item6',
    cardId: 'card4',
    title: 'Write using basic English',
    value: 'Write using basic English',
    order: 6,
  },
  {
    itemId: 'item7',
    cardId: 'card4',
    title: 'Use only scientific sources',
    value: 'Use only scientific sources',
    order: 7,
  },
  {
    itemId: 'item8',
    cardId: 'card4',
    title: 'Add pop culture references',
    value: 'Add pop culture references',
    order: 8,
  },
  {
    itemId: 'item1',
    cardId: 'card5',
    title: 'Give me a list of inexpensive ideas on how to promote my business better.',
    value: 'Give me a list of inexpensive ideas on how to promote my business better.',
    order: 1,
  },
  {
    itemId: 'item2',
    cardId: 'card5',
    title:
      'Acting as a Business Consultant, What is the best way to solve this problem of [Problem]?',
    value:
      'Acting as a Business Consultant, What is the best way to solve this problem of [Problem]?',
    order: 2,
  },
  {
    itemId: 'item3',
    cardId: 'card5',
    title: 'Create a 30-Day Social Media Content Strategy based',
    value: 'Create a 30-Day Social Media Content Strategy based on [Торіс 1] & [Торіс 2].',
    order: 3,
  },
];

export default items;
