import '@/styles/globals.css';
import React from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Prompt Engineering Cheat Sheets',
  description: 'Generated by Sopra Steria',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='min-h-svh'>
      <body className='flex flex-col min-h-svh'>
        <Header />
        <main className='grow'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
